//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIADatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
		private int id;
		private DateTime now;
		private decimal fare;
		private string v;

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Tickets = new HashSet<Ticket>();
        }

		public Booking(int account_id, DateTime booking_datetime, decimal total_fare, string booking_status)
		{
			this.account_id = account_id;
			this.booking_datetime = booking_datetime;
			this.total_fare = total_fare;
			this.booking_status = booking_status;
		}

		public int booking_id { get; set; }
        public int account_id { get; set; }
        public System.DateTime booking_datetime { get; set; }
        public decimal total_fare { get; set; }
        public string booking_status { get; set; }
    
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
