//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIADatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
		private string username;
		private string v;

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Bookings = new HashSet<Booking>();
        }

		public Member(string name, DateTime DOB, string login_username, string email, string image_url)
		{
			this.name = name;
			this.DOB = DOB;
			this.login_username = login_username;
			this.email = email;
			this.image_url = image_url;
		}

		public int id { get; set; }
        public string name { get; set; }
        public System.DateTime DOB { get; set; }
        public string login_username { get; set; }
        public string email { get; set; }
        public string image_url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Login Login { get; set; }
    }
}
