//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIADatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareTariff
    {
        public int flight_id { get; set; }
        public string class_type { get; set; }
        public string child_fare { get; set; }
        public string adult_fare { get; set; }
    
        public virtual FlightRecord FlightRecord { get; set; }
    }
}
