//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIADatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
		private int flight1;
		private string last_name;
		private string first_name;
		private string passport;
		private DateTime dob;
		private string type;
		private string v;

		public Ticket(int booking_id, int flight_id, string passenger_lastname, string passenger_firstname, string passenger_passport, 
			DateTime passenger_dob, string class_type, string ticket_status)
		{
			this.booking_id = booking_id;
			this.flight_id = flight_id;
			this.passenger_lastname = passenger_lastname;
			this.passenger_firstname = passenger_firstname;
			this.passenger_passport = passenger_passport;
			this.passenger_dob = passenger_dob;
			this.class_type = class_type;
			this.ticket_status = ticket_status;
		}

		public int ticket_no { get; set; }
        public int booking_id { get; set; }
        public int flight_id { get; set; }
        public string passenger_lastname { get; set; }
        public string passenger_firstname { get; set; }
        public string passenger_passport { get; set; }
        public System.DateTime passenger_dob { get; set; }
        public string class_type { get; set; }
        public string ticket_status { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual FlightRecord FlightRecord { get; set; }
    }
}
